version: '3'

services:
  # frontend:
  #   container_name: ft_frontend
  #   build: ./frontend/
  #   restart: always
  #   ports:
  #     - "4173:4173"
  #   networks:
  #     ft_transcendence_network:
  #       aliases: [ft_transcendence.frontend]
  #   depends_on:
  #     - backend

  # backend:
  #   container_name: ft_backend
  #   build: ./backend/
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     ft_transcendence_network:
  #       aliases: [ft_transcendence.backend]
  #   depends_on:
  #     - database

  database:
    container_name: ft_database
    image: "postgres:14"
    restart: always
    # env_file:
    #   - ./backend/.env
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    networks:
      ft_transcendence_network:
        aliases: [ft_transcendence.database]
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432


networks:
  ft_transcendence_network:
    driver: bridge

  
volumes:
  postgres:
