version: '3'

services:
  frontend:
    container_name: ft_frontend
    build: ./frontend/
    restart: unless-stopped
    ports:
      - "4173:4173"
      - "5173:4173"
    networks:
      - ft_transcendence_network
    depends_on:
      - backend

  backend:
    container_name: ft_backend
    build: ./backend/
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - ft_transcendence_network
    volumes:
      - statics:/transcendence/static/avatars
    depends_on:
      - database

  database:
    container_name: ft_database
    image: "postgres:14"
    restart: unless-stopped
    # env_file:
    #   - ./backend/.env
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    networks:
      - ft_transcendence_network
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432


networks:
  ft_transcendence_network:


volumes:
  postgres:
  statics:
